# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_400.tex>
# Date: [2020-6-8 19:42:15] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 1> - 

#' Basic setup of corona (Nanny Covid) R program:
#'    On loading corona loads ggplot2, gridExtra, plyr, qicharts 
#'    Use corona(dir='foo') to set the working directory to 'foo'
#'    or just use setwd() as usual. 
#' @param dir 'C:/nc' is default directory, a nasty Windows hack :( 
#' @keywords corona Nanny Covid 
#' @export 
#' @examples
#' corona( dir='C:/foo/bar' ) 
#'
#' You can then invoke the built-in functions like:
#'     corona_rabbits ( )
#'     
#'     corona_country ('France') 
#'     corona_dowjones ( )
#'     corona_lockdown ( ) 
#'     corona_vienna ( ) 
#'     corona_totals ( ) 
#'     corona_alldeaths ( ) 
#'     corona_citymap ( ) 
#'
#' Each of these has associated help e.g. ?corona_vienna 

  # the default is Windows-centric and *nasty* [hmm] 

corona <- function ( dir='C:/nc' )
{ setwd(dir); 
  print("Checking ggplot2, gridExtra, plyr, qicharts2"); 

  if(  ! ( 'ggplot2' %in% (.packages()) )  )
  { stop('Need package ggplot2, please install/load!');
  };
  if(  ! ( 'plyr' %in% (.packages()) )  )
  { stop('Need package plyr, please install/load!');
  };
if(  ! ( 'gridExtra' %in% (.packages()) )  )
  {  stop('Need package gridExtra, please install/load!');
  };
if(  ! ( 'qicharts2' %in% (.packages()) )  )
  {  stop('Need package qicharts2, please install/load!');
  };
  print(  paste( "Working directory is... ", getwd() )  ); 
  print( 'Try  ?corona  for help' ); 
}

# - <Section 2> - 
.onLoad <- function ( libname, pkgname ) 
{ library(gganimate); 
  # hmm, implies: 
  # library(ggplot2); 
  library(gridExtra); 
  library(plyr); 
  library(qicharts2); 
  library(reshape2 ); 
}

# - <Section 3> - 
corona_pdf <- function ( pdfname, w, h, pdf )
{ 
if( ! pdf )
  { return();
  }; 
  pth = './images/'; 
if(! dir.exists(pth) )
  { stop( paste("The directory", pth, "doesn't exist, can't write PDF") );
  }; 
  pathname = paste (pth, pdfname, sep=''); 
  pdf(file=pathname, width=w, height=h); 
} 

# - <Section 4> - 
corona_pdf_off <- function ( pdfname, pdf, waitline = FALSE )
{
if( ! pdf )
  { 
  if(waitline)
    { invisible(readline(prompt="Press [enter] to continue")); 
    }; 
    return();
  }
  dev.off();
  print( paste("Plotted to ", pdfname ) ); 
} 

# - <Section 5> - 
corona_print <- function ( myplot, strip=FALSE )
{
if(strip)  # clunky...
  { p <- myplot + theme( plot.title=element_text(size=18, face="bold"), 
           axis.text.x=element_text(size=10), 
           axis.text.y=element_text(size=10),
           axis.title.x=element_text(size=14),
           axis.title.y=element_text(size=14),
           strip.text = element_text(size = 12),
           strip.text.x = element_text(margin = margin(0,0,0.2,0, "mm"))
           ); 
  } else
  { p <- myplot + theme(plot.title=element_text(size=28, face='bold'), 
        axis.text.x=element_text(size=15), 
        axis.text.y=element_text(size=15),
        axis.title.x=element_text(size=21),
        axis.title.y=element_text(size=21)) + 
    theme_bw(base_size = 20 ); 
  };
  print(p); 
} 

# - <Section 6> - 
corona_unlabelled <- function ( p )
{ return( p + 
     theme( axis.text.x=element_blank(), axis.text.y=element_blank(),
            axis.ticks=element_blank(),
            axis.title.x=element_blank(), axis.title.y=element_blank(),
            panel.background=element_blank(),panel.border=element_blank(),
            panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
            plot.background=element_blank() 
        ) ); 
}

# - <Section 7> - 
corona_check <- function ( p )
{ 
if(  ! ( p %in% (.packages()) )  )
  { stop( paste( 'Need package', p, 'please install/load!') );
  };
}

# - <Section 8> - 
#########################################
#' Generate all Figures in the book 'I Nanny Rona' (printing to PDF)
# '    
#'     Work through and generate PDFs for all examples. 
#' @keywords corona Nanny Covid book print PDF Figures 
#' @export 
#'

corona_all <- function ( )
{ corona_rabbits (pdf=TRUE);
  flush.console();
  corona_country ('United States', pdf=TRUE);
  corona_country ('United Kingdom', pdf=TRUE);
  corona_country ('Germany', pdf=TRUE);
  corona_country ('Italy', pdf=TRUE);
  corona_country ('Spain', pdf=TRUE);
  corona_country ('Taiwan', pdf=TRUE);
  corona_country ('Vietnam', pdf=TRUE);
  corona_country ('South Korea', pdf=TRUE);
  corona_country ('Australia', pdf=TRUE);
  corona_country ('Austria', pdf=TRUE);
  corona_country ('China', pdf=TRUE);
  corona_country ('Thailand', pdf=TRUE);
  corona_country ('Bangladesh', pdf=TRUE);
  corona_country ('Colombia', pdf=TRUE);
  corona_country ('Russia', pdf=TRUE);
  corona_country ('United Arab Emirates', pdf=TRUE);
  corona_country ('Niger', pdf=TRUE);
  corona_country ('New Zealand', pdf=TRUE);
  corona_country ('Singapore', pdf=TRUE);
  flush.console();

  corona_dowjones (pdf=TRUE);
  corona_lockdown (pdf=TRUE); 
  corona_vienna (pdf=TRUE);
  flush.console();

  corona_totals (pdf=TRUE);  # defaults to Italy
  corona_totals (pdf=TRUE, log=TRUE, smooth=TRUE);  
  corona_totals (pdf=TRUE, log=TRUE, dayend=90, smooth=TRUE, prefix='extended');
  flush.console();

  corona_alldeaths (pdf=TRUE);
  flush.console();

  corona_citymap (pdf=TRUE);
  corona_life (filename='animation.gif', side=25, steps=100, density=0.2);  
}
## the end. ##
# -END OF FILE- 
