# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_400.tex>
# Date: [2020-6-8 19:42:15] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 28> - 
#' Plot citymapper data against COVID-19 diagnoses, over time. 
#'
#' Requires ggplot2, plyr and the data frames lock, owid, citymap 
#'    Multiple, select frames are plotted. 
#' 
#' @param pdf = TRUE writes to PDF, default FALSE
#' @param cols Number of columns in output, default is 4 
#' @keywords corona countries daily rates citymapper citymap 
#' @export 
#' @examples
#' corona_citymap(pdf=TRUE, cols=4); 
# ' 


corona_citymap <- function ( pdf=FALSE, FewCities=NULL, cols=4 ) 
{ OW <- owid[order(owid$location),];

  # subset to just the following: [must allow this as optional argument, explore] 
  # 
if( is.null(FewCities) )
  { 
  FewCities <- c('Australia', 'Brazil', 'Canada', 'Denmark',
               'France', 'Germany', 'Japan', 'Mexico', 
               'Russia', 'Singapore', 'South Korea', 'Spain', 
               'Sweden', 'Turkey', 'United Kingdom', 'United States'); 
  }; 

  ####################################################################
  # SMOOTH BY FACTOR [this should share a common function, explore] 
  # 
  smfx <- function ( x )
  {
    FOO <- loess(x$new_cases ~ as.numeric(x$date), span=0.2); # don't use a value < 0.1 
    smoother <- FOO$fitted; 
    ## print(  c('Inrow', as.character(nrow(x)), 'Outrow', as.character(length(smoother)) )  ) 
    data.frame(smoother); 
  }; 
  SMOO <- ddply(OW, .(location), smfx ); 
  # head(SMOO); 
  OW$smoothed <-SMOO$smoother; 
  ####################################################################

  maxcases <- aggregate(OW$smoothed, by=list(OW$location), max); 
  names(maxcases)[1] <- 'location'; 
  names(maxcases)[2] <- 'max_rate';
  OW$max <- maxcases[match(OW$location, maxcases$location),2]
  OW$scaled <- 100.0 * OW$smoothed / OW$max; 

  ## now map {country,date,rate} to owid.
  ## In other words, for each location(country) in owid that has a matching country column in citymap :
  ##   for every date that has a matching date in the Date column, insert the corresponding value from
  ##   the column with that country name. 

  # 1. remove all rows from OW where there's no match to the names of the columns in citymap. 
  # 2. remove rows from OW where date isn't between min:max dates in citymap. 
  # 3. use ddply to apply a dayfx_() function to each date, using date and location to map from citymap
  # 4. map in the new column of values. 

  # exclude missing country names: 
  TopNames <- mapply(gsub, pattern = '[.]', replacement = ' ', names(citymap)); 
  OW <- OW[ OW$location %in% TopNames, ] ;

  ##### lockdown dates: NB. These must match up [explore] 
  OW$lock <- lock[match(OW$location, lock$location), 2];
                                            ## nasty ^

  ###########################################################
  # it would be nice just to say: 
  #    stack(citymap);
  # but there are missing rows in OW for some locations. 

  cityfx <- function ( x )
  { colnam <- gsub( pattern=' ', replacement='.', x[1, 'location']); 
    print(paste('Location is', colnam)); 
    foo <- 100 * citymap[ citymap$Date %in% x$date, colnam];
    bar <- x[ x$date %in% citymap$Date, ]; 
    data.frame( traffic = foo, date = bar$date, scaled = bar$scaled, lock = bar$lock ); 
  };

  CITYUSE <- ddply(OW, .(location), cityfx ); 
  CITYUSE <- CITYUSE[ CITYUSE$location %in% FewCities, ];
  OW <- OW[ OW$location %in% FewCities, ]; 

  LOCKED = 'red';
  TRAFFIC = 'blue'; 
  bas = c(LOCKED, TRAFFIC); 
  citymain <- "New Cases v Traffic Data"; 

  #######################################################################
 
  PdfFilename <- 'citymapper.pdf';
  corona_pdf(PdfFilename, 10, 7, pdf); 

  plotall <- ggplot(CITYUSE, aes(x=date, y=scaled)) + 
                    # or use smoothed ^

       scale_color_identity(guide = 'legend', name=' ', 
               breaks=bas, labels=c( 'lockdown', 'traffic')) + 

       geom_line() + 
       labs(title=citymain, x='Date', y='Cases/Maximum cases') + 
       coord_cartesian( ylim = c(0, 100)) + 
       facet_wrap(vars(location), ncol=cols) + 

      geom_vline( data=OW, aes(xintercept=lock, colour=LOCKED) ) + 

      geom_line( data=CITYUSE, aes(x=date, y=traffic, colour=TRAFFIC) ) + 

    theme( plot.title=element_text(size=18, face="bold"), 
           axis.text.x=element_text(size=10), 
           axis.text.y=element_text(size=10),
           axis.title.x=element_text(size=14),
           axis.title.y=element_text(size=14),
           strip.text = element_text(size = 12),
           strip.text.x = element_text(margin = margin(0,0,0.2,0, "mm"))
         ); 
  # Note use of strip.text.x ; cf corona_print(myplot); 
  print(plotall); 
  corona_pdf_off(PdfFilename, pdf); 
}
#end. 

# - <Section 29> - 






# -END OF FILE- 
