# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_500.tex>
# Date: [2020-7-26 17:40:3] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 13> - 
#' Animate Conway's Game of Life
#' 
#'  The canvas (arena) wraps around vertically and horizontally!  
#' 
#' @param filename writes to this file name e.g. foo.gif (NULL for current GIF device)
#' @param side The number of elements on the area's side (width or height)
#' @param steps The number of frames
#' @param density 0.0--1 The density of the initial, random items
#' @param pattern Defaults to 'random' but there are many other well-known options:
#'    blinker block beehive ttetromino rpentomino snake eater toad 
#'    beacon clock pulsar pentadecathlon galaxy spaceship 
#'    glidergun piheptomino switchengine
#' @keywords corona Conway game of life animation frames 
#' @export 
#' @examples
#' corona_life ( filename='animation.gif', side=50, steps=500, density=0.2 ) 
#' corona_life ( side=100, steps=1000, pattern='rpentomino', wrap=FALSE ) 
#' corona_life ( side=30, steps=120, pattern='spaceship' ) 
#' corona_life ( side=100, steps=400, pattern='switchengine' ) 
#' corona_life ( side=20, steps=30, pattern='clock' ) 
#' corona_life ( side=20, steps=30, pattern='galaxy' ) 

corona_life <- function (filename=NULL, side=50, steps=100, density=0.3, 
                         pattern='random', wrap=TRUE)
{ ARENA <- matrix(nrow=side, ncol=side);
if(pattern == 'random')
  { ARENA[] <- rbinom(side^2,1,density);
  } else
  { mid <- as.integer(side/2); 
    ARENA[] <- rep(0, times=side*side); 
    ARENA <- corona_pattern(ARENA, pattern, x=mid, y=mid);
  }; 
  STORE <- melt( game_of_life(ARENA, steps, wrap) ); 
  names(STORE) <- c('x', 'y', 'frame', 'on');
  STORE <- STORE[ STORE$on==1, ]; 
  print( paste('Starting ', side, 'x', side, 'animation...', steps, 'frames') ); 
  flush.console();

  p <- ggplot(STORE, aes(x = x, y = y)) + 
         geom_tile(color = "green") +
         scale_x_continuous(limits=c(0, side), expand = c(0, 0)) + 
         scale_y_continuous(limits=c(0, side), expand = c(0, 0)) + 
         coord_equal(); 
  p <- corona_unlabelled(p); 

  anim <- p + ggtitle('Frame {frame} of {nframes}') + 
  transition_states(frame,
                    transition_length = 1,
                    state_length = 1);
if( is.null(filename) )
  { print(anim, nframes=steps); 
    print('Animation written to default output'); 
  } else
  { pth = './images/'; 
  if(! dir.exists(pth) )
    { stop( paste("The directory", pth, "doesn't exist, can't write", filename) );
    }; 
    pathname = paste (pth, filename, sep=''); 
    anim_save( pathname, animation=anim, nframes=steps ); # defaults to last_animation() 
    print( paste('Animation written to ', pathname) ); 
  }; 
  flush.console(); 
} 

# - <Section 14> - 
game_of_life <- function(ARENA, steps=50, wrap=TRUE)
{ side <- nrow(ARENA); # assumes side x side square matrix
  q <- side-1; 
  STORE <- array(0, c(side, side, steps));

  rotR <- function(A, L)
    { return( c(A[L], A[1:L-1]) ); 
    };
  rotL <- function(A, L)
    { return( c(A[2:L], A[1]) );
    }; 
                              
for (i in 1:steps)
  { # rows/columns Top Right Bottom Left: 
  if(wrap)
    { T <- ARENA[1,];
      R <- ARENA[,side];
      B <- ARENA[side,];
      L <- ARENA[,1]; 
    } else
    { T <- R <- B <- L <- rep(0, times=side);
    }; 

    # make 8 shifted copies of the original array
    allW <- cbind(R, ARENA[,-side] ); # West is shifted 'right'
    allN <- rbind(B, ARENA[-side,]);  # North is shifted 'down' etc. 
    allE <- cbind(ARENA[,-1], L);
    allS <- rbind(ARENA[-1,], T);
    allNW <- rbind(rotR(B,side),cbind(R[1:q],ARENA[-side,-side]));
    allNE <- rbind(rotL(B,side),cbind(ARENA[-side,-1],L[1:q]));
    allSE <- rbind(cbind(ARENA[-1,-1],L[2:side]),rotL(T,side));
    allSW <- rbind(cbind(R[2:side],ARENA[-1,-side]),rotR(T,side));

    # Add matrices
    ARENA2 <- allW + allNW + allN + allNE + allE + allSE + allS + allSW;
	      
    # Apply GoL rules: 
    ARENA3 <- ARENA; 
    ARENA3[ARENA==0 & ARENA2==3] <- 1; 
    ARENA3[ARENA==1 & ARENA2<2] <- 0;
    ARENA3[ARENA==1 & ARENA2>3] <- 0;
    ARENA <- ARENA3;
	
    STORE[,,i] <- ARENA; 
  }
  return(STORE); 
}

# - <Section 15> - 
corona_pattern <- function(ARENA, pattern, x=5, y=5)
{ PTN <- life[ life$pattern == pattern, ]; 
for( i in 1:nrow(PTN) )
  { ARENA[ x+PTN$x[i], y+PTN$y[i] ] <- 1;
  }; 
  return(ARENA); 
}
# -END OF FILE- 
