# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_500.tex>
# Date: [2020-7-26 17:40:3] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 6> - 
#' Plot time course of coronavirus case incidence and deaths for one country 
#'
#'   The daily case rate is also shown as a smoothed curve.
#'   The smoothed death incidence is MULTIPLIED x5 to highlight
#'   its relationship to the incidence curve. See grown-up documentation (LyX) 
#' 
#' @param cntry : no default
#' @param pdf : defaults to FALSE. If TRUE, writes to country_name_new.pdf
#'     i.e. '_new.pdf' is appended to formal country name. 
#'     If the country name contains spaces ' ' they are changed to underscores '_' 
#' 
#' @keywords corona single country 
#' @export 
#' @examples
#' corona_country('United States', pdf=FALSE); 
#' corona_country('United States', pdf=TRUE); 
#' corona_country('Taiwan', pdf=TRUE); 

corona_country <- function(cntry, pdf=FALSE, smooth=TRUE, deaths=TRUE)
{ CTRY <- owid[ owid$location==cntry, ]; 
if( nrow(CTRY) < 1 )
  { stop( paste('No data for ', cntry) ); 
  }; 
  CTRY$five <- 5*CTRY$new_deaths; 

  ctitle <- cntry; 
  ymax <- max(CTRY$new_cases); 
  yco <- 0.8 * ymax; 
  cols <- ncol(CTRY);
  xco <- CTRY$date[as.integer(0.5*cols)];
  smoothing <- 0.2; 

  FIVETIMES='red';
  NEWCASES='grey40'; 
  NEWDEATHS='darkred';
  SMOOT='black';

  lty <- 'dashed'; 
  fname <- cntry; 
  fname <- gsub( ' ', '_', fname); # replace ' ' with '_' 
if(! deaths)
  { fname <- paste(fname, '_simple', sep=''); 
  }; 
if(! smooth)
  { lty <- 'solid'; # cases are dashed if smoothed line drawn.
    fname <- paste(fname, '_plain', sep=''); 
  }; 

  legendtitle = 'Daily cases'; 
  bar = c(NEWCASES, SMOOT, NEWDEATHS, FIVETIMES);
  labs = c('new cases', 'smoothed', 'new deaths', '5x new deaths, smoothed'); 
  fname <- paste(fname, '_new.pdf', sep='' ); 

  corona_pdf(fname, 11, 7, pdf); 
  myplot <- ggplot(CTRY, aes(x=date)) + 
       # bizarre colour mapping: 
       scale_color_identity(guide = 'legend', name=legendtitle, breaks=bar, labels=labs) + 
       geom_line( aes(y=new_cases, colour=NEWCASES), linetype=lty ) + 
       labs(title=ctitle, x='Date', y='Cases/Deaths per day'); 

if(smooth)
  { myplot <- myplot + 
      geom_smooth( aes(y=new_cases, colour=SMOOT), method='loess', span=smoothing, linetype='solid' ); 
  }; 

if(deaths)
  { myplot <- myplot + geom_line( aes(y=new_deaths, colour=NEWDEATHS), linetype='solid' );
  if(smooth)
    { yup <- 0.08 * max(CTRY$new_cases); 
      Lfive <- loess(five~as.numeric(date), data=CTRY, span=smoothing, na.action=na.exclude); 
      Pfive <- predict(Lfive); 
      yfive <- max( Pfive );
      xfive <- min( CTRY$date[Pfive==yfive] ); 
      myplot <- myplot + 
        annotate('text', x=xfive, y=(yfive+yup), colour=FIVETIMES, size=16, label='×5') + 
        geom_smooth( aes(y=five, colour=FIVETIMES), method='loess', span=smoothing, linetype='solid' ); 
    }; 
  }; 

  corona_print(myplot); 
  corona_pdf_off(fname, pdf); 
}
# end. 
# -END OF FILE- 
