# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_400.tex>
# Date: [2020-6-8 19:42:15] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 24> - 
#' Plot time course of coronavirus case incidence and deaths for one country. 
#'
#' Requires ggplot2. 
#'   The daily case rate is also shown as a smoothed curve.
#'   The smoothed death incidence is MULTIPLIED x5 to highlight
#'   its relationship to the incidence curve. See grown-up documentation (LyX) 
#' ASSUMES that owid data set is loaded. 
#' 
#' @param cntry : no default
#' @param pdf : defaults to FALSE. If TRUE, writes to country_name_new.pdf
#'     where '_new.pdf' is appended to formal country name. 
#'     If the country name contains spaces ' ' they are changed to underscores '_' 
#' 
#' @keywords corona single country 
#' @export 
#' @examples
#' corona_country('United States', pdf=FALSE); 
#' corona_country('United States', pdf=TRUE); 
#' corona_country('Taiwan', pdf=TRUE); 

corona_country <- function(cntry, pdf=FALSE)
{ 
  corona_check('ggplot2'); 

  CTRY <- owid[ owid$location==cntry, ]; 
if( nrow(CTRY) < 1 )
  { stop( paste('No data for ', cntry) ); 
  }; 

  CTRY$five <- 5*CTRY$new_deaths; 

  ctitle <- cntry; 
  ymax <- max(CTRY$new_cases); 
  yco <- 0.8 * ymax; 
  cols <- ncol(CTRY);
  xco <- CTRY$date[as.integer(0.5*cols)];

  FIVETIMES='red';
  NEWCASES='grey40'; 
  NEWDEATHS='darkred';
  SMOOT='black';

  legendtitle = 'Daily cases'; 
  bar = c(NEWCASES, SMOOT, NEWDEATHS, FIVETIMES);
  labs = c('new cases', 'smoothed', 'new deaths', '5x new deaths, smoothed'); 

  fname <- paste(cntry, '_new.pdf', sep='' ); 
  fname <- gsub( ' ', '_', fname); 
  corona_pdf(fname, 11, 7, pdf); 

  myplot <- ggplot(CTRY, aes(x=date)) + 
       # bizarre colour mapping: 
       scale_color_identity(guide = 'legend', name=legendtitle, breaks=bar, labels=labs) + 

       geom_line( aes(y=new_cases, colour=NEWCASES), linetype='dashed' ) + 
       geom_line( aes(y=new_deaths, colour=NEWDEATHS), linetype='solid') + 
       
       geom_smooth( aes(y=new_cases, colour=SMOOT), method='loess', span=0.2, linetype='solid' ) +
       geom_smooth( aes(y=five, colour=FIVETIMES), method='loess', span=0.2, linetype='solid') + 

       labs(title=ctitle, x='Date', y='Cases/Deaths per day') + 
  
    theme( plot.title=element_text(size=18, face='bold'), 
           axis.text.x=element_text(size=10), 
           axis.text.y=element_text(size=10),
           axis.title.x=element_text(size=14),
           axis.title.y=element_text(size=14),
         legend.position = c(0.155, 0.85) 
         ) ;
  # consider modifying corona_print(myplot) parameters [explore]
  print(myplot); 
  corona_pdf_off(fname, pdf); 
}
# end. 

# - <Section 25> - 






# -END OF FILE- 
