# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_903.tex>
# Date: [2020-9-7 14:44:13] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 24> - 
#' Plot Dow-Jones Closing data 
#' 
#'  Assumes the existence of the data frame djia, part of corona data. 
#' 
#' @param pdf=FALSE will not print to PDF
#' @keywords corona dow jones industrial average 
#' @export 
#' @examples
#' corona_dowjones ( pdf=TRUE ) 

corona_dowjones <- function ( pdf=FALSE )
{ PdfFilename <- 'DJIA.pdf'; 
  corona_pdf(PdfFilename, 12, 6.3, pdf); 
  myplot <- ggplot( djia, aes(x=Date, y=Close)) + 
    geom_line() + 
    labs(title='Dow Jones Industrial Average', x='Date', y='Close') + 
    scale_x_date(breaks="2 year", date_labels = "%Y") ;
  corona_print(myplot); 
  corona_pdf_off(PdfFilename, pdf); 
}
# -END OF FILE- 
