# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_400.tex>
# Date: [2020-6-8 19:42:15] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 30> - 
#' Plot Dow-Jones Closing data. 
#'     Assumes the existence of the data frame djia, part of corona data. 
#' 
#' @param pdf=FALSE will not print to PDF
#' @keywords corona dow jones industrial average 
#' @export 
#' @examples
#' corona_dowjones ( pdf=TRUE ) 

corona_dowjones <- function ( pdf=FALSE )
{ corona_check('ggplot2'); 
  PdfFilename <- 'DJIA.pdf'; 
  corona_pdf(PdfFilename, 12, 5, pdf); 
  myplot <- ggplot( djia, aes(x=Date, y=Close)) + 
    geom_line() + 
    labs(title='Dow Jones Industrial Average', x='Date', y='Close') + 
    scale_x_date(breaks="1 year", date_labels = "%Y") ;
  corona_print(myplot); 
  corona_pdf_off(PdfFilename, pdf); 
}
# end. 
# -END OF FILE- 
