# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_500.tex>
# Date: [2020-7-26 17:40:3] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 12> - 
#' Plot Google Trends data for searches involving the word 'coronavirus'. 
#' 
#'   Just plot the lines. 
#'   Requires the CSV GoogleTrendsWorldCoronavirus.csv as the object gt 
#' 
#' @param pdf=FALSE will *not* print thePDF file
#' @keywords corona coronavirus Google Trends
#' @export 
#' @examples
#' corona_trends ( pdf=TRUE ) 

corona_trends <- function ( pdf=FALSE ) 
{ PlotFilename = 'google_trends_world.pdf';
  corona_pdf(PlotFilename, 11, 7, pdf); 

  myplot <- ggplot( gt, aes(x=Date, y=coronavirus)) + 
    geom_line() + 
    labs(title='Google Searches', x='Date', y='Percent maximum')  
  myplot; 

  corona_print(myplot); 

  corona_pdf_off(PlotFilename, pdf); 
} 
# -END OF FILE- 
