# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_500.tex>
# Date: [2020-7-26 17:40:3] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 7> - 
#' Draw multiple smoothed graphs of new daily cases, with lockdown date, if present 
#'
#'    By default limited to countries with population > 4M, and over 200 cases. 
#' 
#' @param pdf=FALSE By default will not print to PDF
#' @param minpeople Minimum population for the country
#' @param mincases Minimum number of COVID-19 cases
#' @param cols Number of columns to display, default = 7
#' @param striptextsize size of text in country names
#' @keywords corona lockdown smoothed 
#' @export 
#' @examples
#' corona_lockdown( cols=14 ) 
#' corona_lockdown( pdf=TRUE ) 

corona_lockdown <- function ( pdf=FALSE, minpeople=4000000, mincases=200, cols=7,
   striptextsize=22, legendx=0.86, legendy=0.03)
{ 
  # private function: 
  # uses loess to smooth data supplied as x. 
  corona_smooth_fx <- function ( x )
  {
    FOO <- loess(x$new_cases ~ as.numeric(x$date), span=0.2); # don't use a value < 0.1 
    smoother <- FOO$fitted; 
    data.frame(smoother); 
  };

  LOWID <- owid[order(owid$location),]
  # ^ WE *must* do this owing to the manipulations below being based on sort order! #
  LOWID <- LOWID[ LOWID$population > minpeople, ] 
  LOWID <- LOWID[ ! is.na(LOWID$population), ]
  LOWID <- LOWID[ ! is.na(LOWID$new_cases), ]

  ## limit to those countries with > mincases: 
  totals <- aggregate(LOWID$new_cases, by=list(LOWID$location), sum);
  names(totals)[1] <- 'location';
  names(totals)[2] <- 'total'; 
  LOWID$tot <- totals[match(LOWID$location, totals$location), 2];
  LOWID <- LOWID[ LOWID$tot > mincases, ]

  SMOO <- ddply(LOWID, .(location), corona_smooth_fx ); 
  head(SMOO); 
  ## there is a frame shift if we didn't sort, and say
  LOWID$smoothed <-SMOO$smoother; 

  maxcases <- aggregate(LOWID$smoothed, by=list(LOWID$location), max); 
  names(maxcases)[1] <- 'location'; 
  names(maxcases)[2] <- 'max_rate';

  LOWID$max <- maxcases[match(LOWID$location, maxcases$location),2]
  LOWID$scaled <- 100.0 * LOWID$smoothed / LOWID$max; 

  allmain <- "All Cases";

  LOWID$lock <- lock[match(LOWID$location, lock$location), 2];
  ## ^ naah, move this up. 

  PdfFilename <- 'owid_lockdown.pdf'; 
  corona_pdf(PdfFilename, 21, 30, pdf); 

  LOCKED = 'red';
  bas = c(LOCKED); 

  myplot <- ggplot(LOWID, aes(x=date, y=scaled)) + 
                    # or use smoothed ^

       scale_color_identity(guide = 'legend', name=' ', 
               breaks=bas, labels=c('lockdown')) + 
       geom_line() + 
       labs(title=allmain, x='Date', y='Cases/Maximum cases') + 
       coord_cartesian( ylim = c(0, 100)) + 
       facet_wrap(vars(location), ncol=cols) + 
       geom_vline( data=LOWID, aes(xintercept=lock, colour=LOCKED) ); 

  corona_print(myplot, striptextsize=22, legendx=legendx, legendy=legendy); 
  corona_pdf_off(PdfFilename, pdf); 
} 
# end. 
# -END OF FILE- 
