# Generated by LaTeX DogWagger Version 4.0.5 from file <NCTLL_500.tex>
# Date: [2020-6-21 15:53:19] 
# Do NOT edit this file. Edit the LaTeX source!!

# - <Section 6> - 
#' Plot UK deaths by week, with various adjustments:
#'
#' Assumes the existence of the data frame ukdead. 
#'   Draws three graphs:
#'   1. Raw data with a linear regression line; 
#'   2. Data with secular adjustment; 
#'   3. Data adjusted for a 'summer baseline' using the "other 9 years of data" after
#'      secular adjustment.  
#' 
#' @param pdf=FALSE will not print to PDF
#' @keywords corona rabbits
#' @export 
#' @examples
#' corona_alldeaths( pdf=TRUE ) 

corona_alldeaths <- function ( pdf=FALSE ) 
{ 
  # at present ONLY applies to UK. 
  mytitle <- "UK Weekly Deaths"; 

#########################################################
  secular_fix <- function (F) # F is the frame.
  { mylm <- lm(F$Deaths ~ F$Week);
    yint <- mylm$coefficients[1];
    slp <- mylm$coefficients[2]; 
    WTOT <- nrow(F); 
    # print( c('Adjustment parameters: slope =', slp, 'y intercept ', yint, 'N=', WTOT) ); 
    F$secular <- F$Deaths * ( 1 + slp*(1+WTOT-F$Week)/yint ); 
    return(F);
  };

  #########################################################
  # look for secular change: 
  MYDEAD <- secular_fix(ukdead); 

  #####################################
  # eye candy with regression line. 
  PdfFilename = 'uk_weekly_dead.pdf'; 
  corona_pdf(PdfFilename, 12, 7, pdf); 

  myplot <- ggplot( MYDEAD, aes(x=Date, y=Deaths)) + 
    geom_point() + 
    geom_line() + 
    labs(title=mytitle, x='Date', y='Deaths') + 
    geom_smooth(method='lm') + 
    scale_x_date(breaks="1 year", date_labels = "%Y") ;
  corona_print(myplot); 
  corona_pdf_off(PdfFilename, pdf, waitline=TRUE);  

  #########################################
  # with secular adjustment:
  SecularFilename = 'uk_weekly_secular.pdf'; 
  corona_pdf(SecularFilename, 12, 7, pdf); 

  secplot <- ggplot( MYDEAD, aes(x=Date, y=secular)) + 
    geom_point() + 
    geom_line() + 
    labs(title=mytitle, x='Date', y='Deaths(adj)') + 
    geom_smooth(method='lm') + 
    scale_x_date(breaks="1 year", date_labels = "%Y") ;
  corona_print(secplot); 
  corona_pdf_off(PdfFilename, pdf, waitline=TRUE);

  ############################################
  # seasonal. To get summer:
  MYDEAD$summer <- as.integer(format(MYDEAD$Date, '%m')); 
  MYDEAD$summer <- (MYDEAD$summer >= 6) & (MYDEAD$summer <= 8); 
  SUMSECAVG <- mean( MYDEAD[ MYDEAD$summer, ]$secular ); 
  # the benchmark adjustment is the sum of other 9 most recent corresponding weeks  
  #   divided by 9 and then DIVIDED INTO the current value. 

  ######## testing
  MYDEAD$bm <- MYDEAD$Week %% 52;
  weekmean <- tapply(MYDEAD$secular[1:520], MYDEAD$bm[1:520], mean);
  MYDEAD$adjust <- weekmean[ 1+MYDEAD$bm ];
  MYDEAD$expected <- weekmean[ 1+MYDEAD$bm ];

  # next, remove own value from mean: 
  MYDEAD$adjust[1:520] <- (10*MYDEAD$adjust[1:520] - MYDEAD$secular[1:520])/9; 
  ## ^ do not adjust final values over 520 i.e. in 2020, as they haven't been included! 
  # we now want to replace MYDEAD$bm by the corresponding indexed value in BCH 
  # now normalise to SUMSECAVG, the summer secular average. 
  MYDEAD$adjust = MYDEAD$adjust/SUMSECAVG; 
  # finally, adjust
  MYDEAD$seasonal <- MYDEAD$secular/MYDEAD$adjust; 
 
  ### display:
  # plot(x=MYDEAD$Date, y=MYDEAD$seasonal);
  # lines(x=MYDEAD$Date, y=MYDEAD$seasonal); 

  # #################
  # qic(x=MYDEAD$Date, y=MYDEAD$seasonal, chart='i',
  #        title='Seasonally Adjusted Deaths', xlab='Year', ylab='Deaths'); 
  #	PARTIAL <- MYDEAD[468:537,]; 
  #	qic(x=PARTIAL$Date, y=PARTIAL$seasonal, chart='i',
  #	          title='Seasonally Adjusted Deaths', xlab='Year', ylab='Deaths'); 
  ################################################################################## 
  AdjustedFilename = 'uk_weekly_adjusted.pdf'; 
  corona_pdf(AdjustedFilename, 12, 7, pdf); 
  mychart <- qic(x=MYDEAD$Date, y=MYDEAD$seasonal, chart='i',
          title='Seasonally Adjusted Deaths', xlab='Year', ylab='Deaths'); 
  print(mychart); 
  corona_pdf_off(AdjustedFilename, pdf); 

  # write.csv(MYDEAD, file='mydead.csv') # if need adjusted data. 
} 
# end. 
# -END OF FILE- 
